# Generated by Django 5.2.5 on 2025-11-09 13:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('get_new_pass', '0007_passapplication_receipt_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('issue_time', models.TimeField(default=django.utils.timezone.now)),
                ('student_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('sub_admin_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('admin_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('amount_transferred', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='get_new_pass.passapplication')),
            ],
        ),
    ]
