# Generated by Django 5.2.5 on 2025-11-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuePass',
            fields=[
                ('pass_number', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_id', models.CharField(max_length=50, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('student_class', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IssuedPass',
        ),
    ]
