# Generated by Django 5.2.5 on 2025-11-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_system', '0002_issuepass_delete_issuedpass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuepass',
            options={'ordering': ['-issue_date'], 'verbose_name': 'Issue Pass', 'verbose_name_plural': 'Issued Passes'},
        ),
        migrations.AlterField(
            model_name='issuepass',
            name='receipt_id',
            field=models.CharField(max_length=50),
        ),
    ]
