# Generated by Django 5.2.5 on 2025-11-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_system', '0003_alter_issuepass_options_alter_issuepass_receipt_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuepass',
            options={},
        ),
        migrations.AddField(
            model_name='issuepass',
            name='admin_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/admin/'),
        ),
        migrations.AddField(
            model_name='issuepass',
            name='application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuepass',
            name='application_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuepass',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='issuepass',
            name='pass_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='issuepass',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='issuepass',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuepass',
            name='student_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/student/'),
        ),
        migrations.AddField(
            model_name='issuepass',
            name='sub_admin_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/subadmin/'),
        ),
    ]
