# Generated by Django 5.2.5 on 2025-11-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_system', '0004_alter_issuepass_options_issuepass_admin_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuepass',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
