# Generated by Django 5.2.5 on 2025-11-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_system', '0005_issuepass_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuepass',
            name='student_uploaded_photo',
            field=models.FileField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
