# Generated by Django 5.2.5 on 2025-11-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RenewPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_receipt_id', models.CharField(max_length=20)),
                ('new_receipt_id', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('month', models.CharField(max_length=50)),
                ('student_photo', models.ImageField(upload_to='renew_photos/')),
                ('student_signature', models.ImageField(upload_to='renew_signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
