# Generated by Django 5.2.5 on 2025-11-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renew_pass', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renewpass',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='renewpass',
            old_name='old_receipt_id',
            new_name='original_receipt_id',
        ),
        migrations.RenameField(
            model_name='renewpass',
            old_name='new_receipt_id',
            new_name='receipt_id',
        ),
        migrations.RemoveField(
            model_name='renewpass',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='renewpass',
            name='student_photo',
        ),
        migrations.RemoveField(
            model_name='renewpass',
            name='student_signature',
        ),
        migrations.AddField(
            model_name='renewpass',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='renew_photos/'),
        ),
        migrations.AddField(
            model_name='renewpass',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='renew_signatures/'),
        ),
        migrations.AlterField(
            model_name='renewpass',
            name='month',
            field=models.CharField(max_length=20),
        ),
    ]
