# Generated by Django 5.2.5 on 2025-11-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renew_pass', '0002_rename_student_name_renewpass_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewpass',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
