# Generated by Django 5.2.5 on 2025-11-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renew_pass', '0003_renewpass_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewpass',
            name='receipt_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
