# Generated by Django 5.2.5 on 2025-11-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renew_pass', '0004_alter_renewpass_receipt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewpass',
            name='payment_status',
            field=models.CharField(default='UNPAID', max_length=20),
        ),
    ]
