# Generated by Django 5.2.5 on 2025-11-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=100)),
                ('pass_days', models.IntegerField()),
                ('application_date', models.DateField()),
                ('application_time', models.TimeField()),
            ],
        ),
    ]
