# Generated by Django 5.2.5 on 2025-11-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_new_pass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passapplication',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
