# Generated by Django 5.2.5 on 2025-11-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_new_pass', '0002_passapplication_email_passapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passapplication',
            name='reason',
            field=models.TextField(default='No reason provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passapplication',
            name='application_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='passapplication',
            name='application_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='passapplication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
