# Generated by Django 5.2.5 on 2025-11-08 00:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_new_pass', '0003_passapplication_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passapplication',
            name='application_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='passapplication',
            name='application_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='passapplication',
            name='class_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='passapplication',
            name='pass_days',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='passapplication',
            name='reason',
            field=models.TextField(default='No reason provided'),
        ),
        migrations.AlterField(
            model_name='passapplication',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
