# Generated by Django 5.2.5 on 2025-11-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_new_pass', '0004_passapplication_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passapplication',
            name='reason',
            field=models.TextField(),
        ),
    ]
