# Generated by Django 5.2.5 on 2025-11-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_new_pass', '0005_alter_passapplication_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
