# Generated by Django 5.2.5 on 2025-11-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_new_pass', '0006_alter_passapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passapplication',
            name='receipt_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
