# Generated by Django 5.2.5 on 2025-11-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_new_pass', '0007_passapplication_receipt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='passapplication',
            name='student_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/student/'),
        ),
    ]
