# Generated by Django 5.2.5 on 2025-11-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_new_pass', '0008_passapplication_student_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passapplication',
            name='student_signature',
            field=models.FileField(blank=True, null=True, upload_to='media/signatures/student/'),
        ),
    ]
