# Generated by Django 5.2.5 on 2025-11-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_new_pass', '0009_alter_passapplication_student_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='passapplication',
            name='month',
            field=models.CharField(default='January', max_length=20),
        ),
        migrations.AlterField(
            model_name='passapplication',
            name='student_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/student/'),
        ),
    ]
