# Generated by Django 5.2.5 on 2025-11-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_new_pass', '0010_passapplication_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passapplication',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=20),
        ),
    ]
